shallow_clone: true

platform:
    - x86
    - x64

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          MY_CCTYPE: MSVC141
          MY_TOOLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          MY_CCTYPE: MSVC140
          MY_TOOLDIR: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC

install:
    - '"%MY_TOOLDIR%\vcvarsall.bat" %PLATFORM%'
    - if %PLATFORM%==x86 set WIN64=undef
    - cd win32

build_script:
    - nmake CCTYPE=%MY_CCTYPE%

test_script:
    - nmake CCTYPE=%MY_CCTYPE% test
