shallow_clone: true

image: Visual Studio 2017

install:
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
    - cd win32
    - perl -i.bak -ple "$_ = 'CCTYPE = MSVC141' if m?^CCTYPE\s*=?" Makefile

build_script:
    - nmake

test_script:
    - nmake test
